theme = "ametrine"

title = "Origuchi's Blog"
base_url = "https://blog.origuchi.uk"
description = "Origuchi's Blog"
compile_sass = true
minify_html = true
build_search_index = true
author = "Origuchi"
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
default_language = "en"

taxonomies = [
  { name = "tags", feed = true, paginate_by = 10 },
  { name = "categories", feed = true },
]

[markdown]
smart_punctuation = true
bottom_footnotes = true
external_links_class = "external"
github_alerts = true

[markdown.highlighting]
style = "class"
light_theme = "monokai-pro-light"
dark_theme = "monokai-pro"
extra_themes = [
  "themes/ametrine/giallo/themes/monokai-pro-light.json",
  "themes/ametrine/giallo/themes/monokai-pro.json",
]

[search]
index_format = "elasticlunr_json"

[languages.zh-Hans]
title = "Origuchi's Blog"
description = "Origuchi's Blog"
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
taxonomies = [
  { name = "tags", feed = true, paginate_by = 10 },
  { name = "categories", feed = true },
]

[extra]
categories = [
  { name = "Archived", description = "Posts that have been archived due to their age.", color = "purple", icon = "box-arrow-down" },
  { name = "Featured", description = "Posts that are somewhat decently written.", color = "yellow", icon = "star" },
  { name = "Hot", description = "Posts that did numbers compared to others.", color = "red", icon = "fire" },
  { name = "Test", description = "Categories can be set and customized entirely from config, woo-hoo!", color = "green", icon = "feather" },
]
accent_color = ["blue", "blue"]
source_url = "https://github.com/Tobiichi-Origuchi/myblog"
issues_url = "https://github.com/Tobiichi-Origuchi/myblog/issues/new"
show_reading_time = true
copy_button = true
show_backlinks = true
date_format = "%d %B %Y"
date_format_long = "%d %B %Y, %R (%Z)"
date_locale = "en_US"
timezone = "Asia/Shanghai"
show_comments_qr = true
csp = [
  { directive = "font-src", domains = [
    "'self'",
  ] },
  { directive = "img-src", domains = [
    "'self'",
    "https:",
    "data:",
  ] },
  { directive = "media-src", domains = [
    "'self'",
    "https:",
  ] },
  { directive = "script-src", domains = [
    "cloud.umami.is",
    "static.cloudflareinsights.com",
    "stats.origuchi.qzz.io",
  ] },
  { directive = "style-src", domains = [
    "'self'",
    "'unsafe-inline'",
  ] },
  { directive = "frame-src", domains = [
    "https://player.vimeo.com",
    "https://www.youtube-nocookie.com",
    "https://vmst.io",
  ] },
  { directive = "connect-src", domains = [
    "*.umami.dev",
    "cloud.umami.is",
  ] },
  { directive = "base-uri", domains = [
    "'none'",
  ] },
  { directive = "form-action", domains = [
    "'none'",
  ] },
]

[extra.zh-Hans]
categories = [
  { name = "归档", description = "因发布时间较久而被归档的文章。", color = "purple", icon = "box-arrow-down" },
  { name = "精选", description = "写得相对不错的优质文章。", color = "yellow", icon = "star" },
  { name = "热门", description = "热度远超其他内容的文章。", color = "red", icon = "fire" },
  { name = "测试", description = "分类完全可以通过配置文件进行自定义！", color = "green", icon = "feather" },
]
date_format = "%Y年%m月%d日"
date_format_long = "%Y年%m月%d日 %R (%Z)"
date_locale = "zh_CN"

[extra.meta]
favicon = true
apple_touch_icon = true
card = true

[extra.nav]
icon = "apple-touch-icon.png"
links = [
  { url = "@/blog/_index.md", name = "Blog", icon = "newspaper" },
  { name = "Random 🦄", category = [
    { url = "https://example.org", name = "Eggman", icon = "egg" },
    { url = "https://example.org", name = "Honse", icon = "horse" },
    { url = "http://example.org", name = "Lie", icon = "cake", new = true },
    { url = "http://example.org", name = "No Icon?" },
  ] },
]

[extra.nav.zh-Hans]
links = [
  { url = "@/blog/_index.md", name = "Blog", icon = "newspaper" },
  { name = "随机 🦄", category = [
    { url = "https://example.org", name = "Eggman", icon = "egg" },
    { url = "https://example.org", name = "Honse", icon = "horse" },
    { url = "http://example.org", name = "Lie", icon = "cake", new = true },
    { url = "http://example.org", name = "No Icon?" },
  ] },
]

[extra.footer]
copyright = "© Origuchi, 2025-$YEAR"
show_powered_by = true
show_source = true
show_timestamp = true
socials = [
  { url = "https://github.com/Tobiichi-Origuchi", icon = "github" },
  { url = "https://codeberg.org/tobiichioriguchi", icon = "codeberg" },
  { url = "https://t.me/tobiichioriguchi_3d7253072f40407", icon = "telegram" },
  { url = "https://mastodon.social/@origuchi", icon = "mastodon" },
  { url = "https://x.com/Origuchi12", icon = "x" },
]

[extra.footer.zh-Hans]
copyright = "© Origuchi, 2025-$YEAR"

[extra.fediverse]
host = "mastodon.social"
user = "origuchi"
show_qr = true

[extra.analytics]
service = "umami"
id = "e500936a-fa6e-494d-94b0-20be95993b87"
self_hosted_url = "https://stats.origuchi.qzz.io"
do_not_track = false

[extra.debug]
layout = false
no_styles = false
no_emojis = false
